/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ListYourBusinessRouteImport } from './routes/list-your-business'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TravelFlightBookingRouteImport } from './routes/travel.flight-booking'
import { Route as CitySlugRouteImport } from './routes/city.$slug'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as BusinessSlugRouteImport } from './routes/business.$slug'
import { Route as AuthenticatedFavoritesRouteImport } from './routes/_authenticated/favorites'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedBusinessNewRouteImport } from './routes/_authenticated/business.new'
import { Route as AuthenticatedBusinessSlugEditRouteImport } from './routes/_authenticated/business.$slug.edit'
import { Route as AuthenticatedBusinessSlugClaimRouteImport } from './routes/_authenticated/business.$slug.claim'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ListYourBusinessRoute = ListYourBusinessRouteImport.update({
  id: '/list-your-business',
  path: '/list-your-business',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelFlightBookingRoute = TravelFlightBookingRouteImport.update({
  id: '/travel/flight-booking',
  path: '/travel/flight-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const CitySlugRoute = CitySlugRouteImport.update({
  id: '/city/$slug',
  path: '/city/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessSlugRoute = BusinessSlugRouteImport.update({
  id: '/business/$slug',
  path: '/business/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFavoritesRoute = AuthenticatedFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBusinessNewRoute =
  AuthenticatedBusinessNewRouteImport.update({
    id: '/business/new',
    path: '/business/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBusinessSlugEditRoute =
  AuthenticatedBusinessSlugEditRouteImport.update({
    id: '/business/$slug/edit',
    path: '/business/$slug/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBusinessSlugClaimRoute =
  AuthenticatedBusinessSlugClaimRouteImport.update({
    id: '/business/$slug/claim',
    path: '/business/$slug/claim',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/list-your-business': typeof ListYourBusinessRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/business/$slug': typeof BusinessSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/city/$slug': typeof CitySlugRoute
  '/travel/flight-booking': typeof TravelFlightBookingRoute
  '/business/new': typeof AuthenticatedBusinessNewRoute
  '/business/$slug/claim': typeof AuthenticatedBusinessSlugClaimRoute
  '/business/$slug/edit': typeof AuthenticatedBusinessSlugEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/list-your-business': typeof ListYourBusinessRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/business/$slug': typeof BusinessSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/city/$slug': typeof CitySlugRoute
  '/travel/flight-booking': typeof TravelFlightBookingRoute
  '/business/new': typeof AuthenticatedBusinessNewRoute
  '/business/$slug/claim': typeof AuthenticatedBusinessSlugClaimRoute
  '/business/$slug/edit': typeof AuthenticatedBusinessSlugEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/list-your-business': typeof ListYourBusinessRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/favorites': typeof AuthenticatedFavoritesRoute
  '/business/$slug': typeof BusinessSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/city/$slug': typeof CitySlugRoute
  '/travel/flight-booking': typeof TravelFlightBookingRoute
  '/_authenticated/business/new': typeof AuthenticatedBusinessNewRoute
  '/_authenticated/business/$slug/claim': typeof AuthenticatedBusinessSlugClaimRoute
  '/_authenticated/business/$slug/edit': typeof AuthenticatedBusinessSlugEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/categories'
    | '/list-your-business'
    | '/reset-password'
    | '/search'
    | '/sitemap.xml'
    | '/admin'
    | '/dashboard'
    | '/favorites'
    | '/business/$slug'
    | '/category/$slug'
    | '/city/$slug'
    | '/travel/flight-booking'
    | '/business/new'
    | '/business/$slug/claim'
    | '/business/$slug/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/categories'
    | '/list-your-business'
    | '/reset-password'
    | '/search'
    | '/sitemap.xml'
    | '/admin'
    | '/dashboard'
    | '/favorites'
    | '/business/$slug'
    | '/category/$slug'
    | '/city/$slug'
    | '/travel/flight-booking'
    | '/business/new'
    | '/business/$slug/claim'
    | '/business/$slug/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/categories'
    | '/list-your-business'
    | '/reset-password'
    | '/search'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/favorites'
    | '/business/$slug'
    | '/category/$slug'
    | '/city/$slug'
    | '/travel/flight-booking'
    | '/_authenticated/business/new'
    | '/_authenticated/business/$slug/claim'
    | '/_authenticated/business/$slug/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CategoriesRoute: typeof CategoriesRoute
  ListYourBusinessRoute: typeof ListYourBusinessRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BusinessSlugRoute: typeof BusinessSlugRoute
  CategorySlugRoute: typeof CategorySlugRoute
  CitySlugRoute: typeof CitySlugRoute
  TravelFlightBookingRoute: typeof TravelFlightBookingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list-your-business': {
      id: '/list-your-business'
      path: '/list-your-business'
      fullPath: '/list-your-business'
      preLoaderRoute: typeof ListYourBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travel/flight-booking': {
      id: '/travel/flight-booking'
      path: '/travel/flight-booking'
      fullPath: '/travel/flight-booking'
      preLoaderRoute: typeof TravelFlightBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/city/$slug': {
      id: '/city/$slug'
      path: '/city/$slug'
      fullPath: '/city/$slug'
      preLoaderRoute: typeof CitySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/$slug': {
      id: '/business/$slug'
      path: '/business/$slug'
      fullPath: '/business/$slug'
      preLoaderRoute: typeof BusinessSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/favorites': {
      id: '/_authenticated/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AuthenticatedFavoritesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business/new': {
      id: '/_authenticated/business/new'
      path: '/business/new'
      fullPath: '/business/new'
      preLoaderRoute: typeof AuthenticatedBusinessNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business/$slug/edit': {
      id: '/_authenticated/business/$slug/edit'
      path: '/business/$slug/edit'
      fullPath: '/business/$slug/edit'
      preLoaderRoute: typeof AuthenticatedBusinessSlugEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business/$slug/claim': {
      id: '/_authenticated/business/$slug/claim'
      path: '/business/$slug/claim'
      fullPath: '/business/$slug/claim'
      preLoaderRoute: typeof AuthenticatedBusinessSlugClaimRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFavoritesRoute: typeof AuthenticatedFavoritesRoute
  AuthenticatedBusinessNewRoute: typeof AuthenticatedBusinessNewRoute
  AuthenticatedBusinessSlugClaimRoute: typeof AuthenticatedBusinessSlugClaimRoute
  AuthenticatedBusinessSlugEditRoute: typeof AuthenticatedBusinessSlugEditRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFavoritesRoute: AuthenticatedFavoritesRoute,
  AuthenticatedBusinessNewRoute: AuthenticatedBusinessNewRoute,
  AuthenticatedBusinessSlugClaimRoute: AuthenticatedBusinessSlugClaimRoute,
  AuthenticatedBusinessSlugEditRoute: AuthenticatedBusinessSlugEditRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CategoriesRoute: CategoriesRoute,
  ListYourBusinessRoute: ListYourBusinessRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BusinessSlugRoute: BusinessSlugRoute,
  CategorySlugRoute: CategorySlugRoute,
  CitySlugRoute: CitySlugRoute,
  TravelFlightBookingRoute: TravelFlightBookingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
